# Form implementation generated from reading ui file 'NewForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_new_cost_estimate_window(object):
    def setupUi(self, new_cost_estimate_window):
        new_cost_estimate_window.setObjectName("new_cost_estimate_window")
        new_cost_estimate_window.resize(674, 455)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_cost_estimate_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=new_cost_estimate_window)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Change_directory_button = QtWidgets.QPushButton(parent=new_cost_estimate_window)
        self.Change_directory_button.setObjectName("Change_directory_button")
        self.gridLayout.addWidget(self.Change_directory_button, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=new_cost_estimate_window)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=new_cost_estimate_window)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.label_5 = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(parent=new_cost_estimate_window)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=new_cost_estimate_window)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.lineEdit)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_4.setBuddy(self.lineEdit_3)
        self.label.setBuddy(self.plainTextEdit)

        self.retranslateUi(new_cost_estimate_window)
        self.buttonBox.accepted.connect(new_cost_estimate_window.accept) # type: ignore
        self.buttonBox.rejected.connect(new_cost_estimate_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(new_cost_estimate_window)
        new_cost_estimate_window.setTabOrder(self.lineEdit, self.Change_directory_button)
        new_cost_estimate_window.setTabOrder(self.Change_directory_button, self.lineEdit_3)

    def retranslateUi(self, new_cost_estimate_window):
        _translate = QtCore.QCoreApplication.translate
        new_cost_estimate_window.setWindowTitle(_translate("new_cost_estimate_window", "Utwórz nowy kosztorys"))
        self.label_2.setText(_translate("new_cost_estimate_window", "Folder docelowy"))
        self.Change_directory_button.setText(_translate("new_cost_estimate_window", "Zmień"))
        self.label_3.setText(_translate("new_cost_estimate_window", "Nazwa pliku"))
        self.label_4.setText(_translate("new_cost_estimate_window", ".rdsx"))
        self.label.setText(_translate("new_cost_estimate_window", "Opis kosztorysu"))
        self.label_5.setText(_translate("new_cost_estimate_window", "Wersja programu: "))
        self.label_7.setText(_translate("new_cost_estimate_window", "Rozmiar pliku:"))
        self.label_6.setText(_translate("new_cost_estimate_window", "Data modyfikacji:"))
