CURRENCY_SYMBOL = "zł"
DECIMAL_PLACES = 2

MATERIAL_COLUMN = ("MATERIAŁ", "A")
ID_COLUMN = ("ID", "B")
DESCRIPTION_COLUMN = ("OPIS", "C")
UOM_COLUMN = ("J.M.", "D")
QUANTITY_COLUMN = ("ILOŚĆ", "E")
PRICE_COLUMN = ("CENA", "F")
NET_VALUE_COLUMN = ("WARTOŚĆ NETTO", "G")
STOCK_COLUMN = ("STAN NA MAGAZYNIE","H")

COLUMNS = [
    MATERIAL_COLUMN,
    ID_COLUMN,
    DESCRIPTION_COLUMN,
    UOM_COLUMN,
    QUANTITY_COLUMN,
    PRICE_COLUMN,
    NET_VALUE_COLUMN,
    STOCK_COLUMN
]
